# Generated by Django 3.1.6 on 2022-09-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('login', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('logo', models.CharField(max_length=300)),
                ('owner_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerpassword', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(editable=False)),
                ('note', django_cryptography.fields.encrypt(models.CharField(max_length=500))),
                ('owner_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownernote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
