# Generated by Django 3.1.6 on 2022-09-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0002_notes_passwordcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='last_edit',
        ),
        migrations.RemoveField(
            model_name='passwordcard',
            name='created',
        ),
        migrations.RemoveField(
            model_name='passwordcard',
            name='last_edit',
        ),
    ]
