# Generated by Django 3.1.6 on 2022-09-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0003_auto_20220911_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
