# Generated by Django 3.1.6 on 2022-09-20 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0005_auto_20220920_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordcard',
            name='owner_password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwordsuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
