# Generated by Django 3.1.6 on 2022-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0008_auto_20220925_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcard',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
