# Generated by Django 3.1.6 on 2022-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0009_auto_20220925_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
