# Generated by Django 3.1.6 on 2022-09-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypasswords', '0010_auto_20220925_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordcard',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
